spring:
  application.name: api-gateway-ws
  aop:
    proxy-target-class: true
  security:
    user:
      password: password

eureka.client.serviceUrl.defaultZone: ${EUREKA_URL:http://localhost:7100/eureka}

server.port: ${PORT:7000}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user


security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user


healthServers:
  - https://api-gateway-ws.herokuapp.com
  - https://eureka-ws.herokuapp.com
  - https://api-gateway-ws.herokuapp.com/customers-ws
  - https://api-gateway-ws.herokuapp.com/products-ws
  - https://api-gateway-ws.herokuapp.com/orders-ws
  - https://api-gateway-ws.herokuapp.com/carts-ws
wakeupServers:
  - https://api-gateway-ws.herokuapp.com
  - https://eureka-ws.herokuapp.com
  - https://customers-ws.herokuapp.com
  - https://products-ws.herokuapp.com
  - https://orders-ws.herokuapp.com
  - https://carts-ws.herokuapp.com


edge-hostname: https://jaarques-uoc.github.io