spring.application.name: api-gateway-ws

eureka.client.serviceUrl.defaultZone: ${EUREKA_URL:http://localhost:7100/eureka}

server.port: ${PORT:7000}

feign:
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

healthServers:
  - https://api-gateway-ws.herokuapp.com
  - https://eureka-ws.herokuapp.com
  - https://api-gateway-ws.herokuapp.com/customers-ws
  - https://api-gateway-ws.herokuapp.com/products-ws
  - https://api-gateway-ws.herokuapp.com/orders-ws
  - https://api-gateway-ws.herokuapp.com/carts-ws
wakeupServers:
  - https://api-gateway-ws.herokuapp.com
  - https://eureka-ws.herokuapp.com
  - https://customers-ws.herokuapp.com
  - https://products-ws.herokuapp.com
  - https://orders-ws.herokuapp.com
  - https://carts-ws.herokuapp.com
initServers:
  - https://api-gateway-ws.herokuapp.com/customers-ws
  - https://api-gateway-ws.herokuapp.com/products-ws
  - https://api-gateway-ws.herokuapp.com/orders-ws
  - https://api-gateway-ws.herokuapp.com/carts-ws


edge-hostname: https://jaarques-uoc.github.io