servers:
  - http://localhost:7000
  - http://localhost:7100
  - http://localhost:7001
  - http://localhost:7002
  - http://localhost:7003
  - http://localhost:7004

edge-hostname: http://localhost:3000