healthServers:
  - http://localhost:7000
  - http://localhost:7100
  - http://localhost:7000/customers-ws
  - http://localhost:7000/products-ws
  - http://localhost:7000/orders-ws
  - http://localhost:7000/carts-ws
initServers:
  - http://localhost:7000/customers-ws
  - http://localhost:7000/products-ws
  - http://localhost:7000/orders-ws
  - http://localhost:7000/carts-ws

edge-hostname: http://localhost:3000